"""tipagem de embalagem no banco

Revision ID: 4034b41e2968
Revises: dad912bd2e3a
Create Date: 2026-06-08 13:56:28.458069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4034b41e2968"
down_revision: Union[str, Sequence[str], None] = "dad912bd2e3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("compra", sa.Column("embalagem", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("compra", "embalagem")
    # ### end Alembic commands ###
