"""cria tabela usuarios

Revision ID: 993a828f2858
Revises: 4034b41e2968
Create Date: 2026-06-09 10:02:35.559800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "993a828f2858"
down_revision: Union[str, Sequence[str], None] = "4034b41e2968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compra")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compra",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("item", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "preco_unitario",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("quantidade", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "valor_total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("embalagem", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("compra_pkey")),
    )
    # ### end Alembic commands ###
